server:
  port: 18888
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    refresh:
      enabled: true

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/test/config
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: config-server
      auto-offset-reset: earliest
    client-id: config-server