server:
  port: 18888
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    refresh:
      enabled: true

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/test/config
    bus:
      enabled: true
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: 172.31.207.39:9092
    client-id: config-server